[toolchain]
# Keep in sync with `rust-version` in `Cargo.toml`
channel = "1.83.0"
profile = "minimal"
components = [ "clippy", "rust-src" ]
targets = [ "aarch64-unknown-linux-gnu", "x86_64-pc-windows-gnu", "i686-linux-android", "x86_64-linux-android", "aarch64-linux-android", "armv7-linux-androideabi" ]
