---
name: Android - Build and test
on:
  pull_request:
    paths:
      - '**'
      - '!.github/workflows/**'
      - '.github/workflows/android-app.yml'
      - '!.github/CODEOWNERS'
      - '!audits/**'
      - '!ci/**'
      - '!dist-assets/**'
      - '!docs/**'
      - '!graphics/**'
      - '!desktop/**'
      - '!ios/**'
      - '!test/**'
      - '!scripts/**'
      - '!windows/**'
      - '!**/**.md'
      - '!**/osv-scanner.toml'
  schedule:
    # At 00:00 UTC every day.
    # Notifications for scheduled workflows are sent to the user who last modified the cron
    # syntax in the workflow file. If you update this you must have notifications for
    # Github Actions enabled, so these don't go unnoticed.
    # https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/notifications-for-workflow-runs
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      override_container_image:
        description: Override container image
        type: string
        required: false
      run_firebase_tests:
        description: Run firebase tests
        type: boolean
        required: false
      mockapi_test_repeat:
        description: Mockapi test repeat (self hosted)
        default: '1'
        required: true
        type: string
      e2e_test_repeat:
        description: e2e test repeat (self hosted)
        default: '0'
        required: true
        type: string
      e2e_tests_infra_flavor:
        description: >
          Infra environment to run e2e tests on (prod/stagemole).
          If set to 'stagemole' test-related artefacts will be uploaded.
        default: 'stagemole'
        required: true
        type: string
  # Build if main is updated to ensure up-to-date caches are available
  push:

permissions: {}

env:
  E2E_TEST_INFRA_FLAVOR: ${{ github.event.inputs.e2e_tests_infra_flavor || 'stagemole' }}

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use custom container image if specified
        if: ${{ github.event.inputs.override_container_image != '' }}
        run: echo "inner_container_image=${{ github.event.inputs.override_container_image }}"
          >> $GITHUB_ENV

      - name: Use default container image and resolve digest
        if: ${{ github.event.inputs.override_container_image == '' }}
        env:
          e2e_test_repeat: ${{ github.event.inputs.e2e_test_repeat }}
          infra: ${{ env.E2E_TEST_INFRA_FLAVOR }}
          firebase: ${{ github.event.inputs.run_firebase_tests }}
        run: |
          echo "inner_container_image=$(cat ./building/android-container-image.txt)" >> $GITHUB_ENV
    outputs:
      container_image: ${{ env.inner_container_image }}

  generate-debug-keystore:
    name: Generate debug keystore
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Generate keystore
        if: github.event.inputs.e2e_test_repeat != '0'
        run: >-
          keytool -genkey
          -keystore debug.keystore
          -storepass android
          -alias androiddebugkey
          -keypass android
          -keyalg RSA
          -keysize 2048
          -validity 10000
          -dname "CN=Android Debug,O=Android,C=US"

      - name: Upload keystore
        uses: actions/upload-artifact@v4
        with:
          name: debug-keystore
          path: debug.keystore
          if-no-files-found: error
          retention-days: 7
